language: ruby
rvm:
  - 2.5.3
before_install: gem install bundler -v 2.0.1
notifications:
  - false
scripts:
  - bundle install --jobs=3 --retry=3
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec cucumber