language: ruby
rvm:
  - 2.5.3
before_install: gem install bundler -v 2.0.1
notifications:
  - false
scripts:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:setup
  - bundle exec cucumber