language: ruby
rvm:
  - 2.5.3
bundler_args: --binstubs

before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate

scripts:
  - bundle exec rake ci:tests

services:
  - postgresql

notifications:
  email: false