language: ruby
env:
  - RAILS_ENV=test
rvm:
  - 2.5.3
before_script:
  - gem install bundler -v 2.0.1 --no-ri --no-rdoc
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:setup
script:
  - bundle exec cucumber